name: Login_docker

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github_action_docker:latest

      # - name: Build the latest Docker image
      #   run: docker build . --file ./Dockerfile --tag icareemreozan/github_action_docker:latest
      # - name: Push the latest Docker image
      #   run: docker push icareemreozan/github_action_docker:latest